# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: basic packages
  apt:
    pkg:
      - qemu-guest-agent

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#ansible-collections-ansible-builtin-systemd-service-module
- name: Enable qemu daemon
  systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
