- name: basic packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - qemu-guest-agent

- name: Enable qemu daemon
  systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
