---

- name: Configure pve
  ansible.builtin.shell: |
    set -e
    pvesm set local --content iso,images,images,vztmpl,snippets,import,rootdir
    mkdir -p /etc/ansible-proxmox
    touch /etc/ansible-proxmox/.ansible_configured
  args:
    creates: /etc/ansible-proxmox/.ansible_configured
