---

##### backup folder

- name: Mnt folder
  ansible.builtin.file:
    path: "/mnt"
    recurse: false
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Backup folder
  ansible.builtin.file:
    path: "/mnt/backup"
    recurse: false
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Backup local folder
  ansible.builtin.file:
    path: "/mnt/backup_local"
    recurse: false
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: directory

- name: Configure pve
  ansible.builtin.shell: |
    set -e
    pvesm set local --content iso,images,images,vztmpl,snippets,import,rootdir
    pvesm add dir backup_local --path /mnt/backup_local
    mkdir -p /etc/ansible-proxmox
    touch /etc/ansible-proxmox/.storage_configured
  args:
    creates: /etc/ansible-proxmox/.storage_configured
