---

- name: Deploy pve apt sources
  ansible.builtin.copy:
    src: files/pve-non-enterprise.list
    owner: root
    group: root
    dest: '/etc/apt/sources.list.d/pve-non-enterprise.list'
    mode: '0622'

- name: Remove enterprise pve sources
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Remove enterprise ceph sources
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: Install basic packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - vim
      - nfs-common

- name: Unattended-upgrades for pve
  ansible.builtin.copy:
    src: 'files/unattended-upgrades/51unattended-upgrades'
    dest: '/etc/apt/apt.conf.d/10unattended-upgrades'
    mode: '0644'
  register: unattended_upgrades_pve_settings_set

- name: Dpkg reconfigure unattended-upgrades  # noqa: no-changed-when # noqa: no-handler
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  when: unattended_upgrades_pve_settings_set.changed
