---
- name: Converge
  hosts: all
  vars:
    proxmox_api_host_access_limit: 10.1.0.0/24
    proxmox_hostname: myproxmox
    #proxmox_terraform_api_key: "very secret"
  roles:
    - role: proxmox_install
