---
- name: Verify
  hosts: all
  tasks:
    - name: proxmox config exists
      ansible.builtin.command: test -d /etc/pve
    - name: fail2ban proxmox jail exists
      ansible.builtin.command: test -f /etc/fail2ban/jail.d/proxmox.conf
    - name: fail2ban proxmox filter exists
      ansible.builtin.command: test -f /etc/fail2ban/filter.d/proxmox.conf
    - name: proxmox api secured
      ansible.builtin.command: test -f /etc/default/pveproxy
    - name: No pve in aot sources
      ansible.builtin.shell: test ! -f /etc/apt/sources.list || cat /etc/apt/sources.list | grep -v pve
    #- name: Api user has been created
    #  ansible.builtin.shell: pveum user list | grep terraform-prov@pve
