---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: 'geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    # ANSIBLE_CONFIG: "../../ansible.cfg"

verifier:
  name: ansible
