---

k3s:
  version: v1.32.1+k3s1

fail2ban:
  banaction: iptables

proxmox:
  api_host_access_limit: 10.1.0.0/24
  hostname: myproxmox

users:
  - username: ubuntu
    shell: /bin/bash
    groups: sudo,adm
    keys:
      - 'ssh-ed25519 fake test@local.local'

bastion_users:
  - username: myuser
    keys:
      - 'ssh-ed25519 fake test@local.local'
nut:
  client:
    ups_ip: 10.5.5.5
