---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure default sources list has no entries
      ansible.builtin.shell: cat /etc/apt/sources.list | grep -v "deb"
    - name: Stable repo exists
      ansible.builtin.command: test -f /etc/apt/sources.list.d/stable.sourcess
    - name: Updates repo exists
      ansible.builtin.command: test -f /etc/apt/sources.list.d/updates.sources
    - name: Ensure updates list has the porper url
      ansible.builtin.shell: cat /etc/apt/sources.list.d/updates.sources | grep '\-updates'
    - name: Stable repo exists
      ansible.builtin.command: test -f /etc/apt/sources.list.d/security.sources
    - name: Ensure security list has the porper url
      ansible.builtin.shell: cat /etc/apt/sources.list.d/security.sources | grep 'debian\-security'
