- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - zsh
      - unattended-upgrades
      # upgrade the kernel to 6.5
      - linux-generic-hwe-22.04

## unattended upgrades
- name: configre unattended-upgrades
  shell: dpkg-reconfigure -f noninteractive unattended-upgrades

- name: enable unattended-upgrades
  shell: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections

- name: unattended-upgrades autoupgrades
  copy:
    src: 'files/unattended-upgrades/50unattended-upgrades'
    dest: '/etc/apt/apt.conf.d/50unattended-upgrades'
    mode: '0644'

- name: unattended-upgrades autoupgrades
  copy:
    src: 'files/unattended-upgrades/20auto-upgrades'
    dest: '/etc/apt/apt.conf.d/20auto-upgrades'
    mode: '0644'
