---
name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4
      - name: Lint Ansible Playbook
        # see https://github.com/marketplace/actions/run-ansible-lint
        uses: ansible/ansible-lint@v25.1.3
        with:
          args: "-c .config/ansible-lint.yml"
